from pprint import pprint

from kivy.network.urlrequest import UrlRequest
from kivy.app import App
from kivy.factory import Factory
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.togglebutton import ToggleButton
from kivy.uix.label import Label
from kivy.uix.accordion import AccordionItem
import gspread
from google.oauth2.service_account import Credentials

_TEST_DATA = [
 {'Aadhar Card number': 209002752202,
  'Address': 'M block52',
  'Age of  child as of today': '5 Years 10 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'April 30, 2015',
  'Date of joining ': 'Oct 13, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Mohd Saheed',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Farzana Khatoon',
  'Name of student': 'Aizah Shahid',
  'Phone number (Father)': '',
  'Phone number (Mother)': 7543992278,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 1},
 {'Aadhar Card number': '',
  'Address': 'WZ-92',
  'Age of  child as of today': '5 Years 5 Months 8 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Sep 23, 2015',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": 'Shopkeeper',
  "Father's name ": 'Manoj',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Reena',
  'Name of student': 'Jaishu',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9873733297,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 2},
 {'Aadhar Card number': 346069723512,
  'Address': 'WZ-9 A',
  'Age of  child as of today': '5 Years 10 Months 27 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Apr 4, 2015',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": 'Electrician',
  "Father's name ": 'Durgesh kumar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Chandni singh',
  'Name of student': 'yash',
  'Phone number (Father)': 7834963592,
  'Phone number (Mother)': 8010905280,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 3},
 {'Aadhar Card number': 218374994306,
  'Address': 'M-66',
  'Age of  child as of today': '6 Years 5 Months 2 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Sep 29, 2014',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Santosh kumar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Suman',
  'Name of student': 'Niharika OL',
  'Phone number (Father)': 9582531145,
  'Phone number (Mother)': 8860147896,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 4},
 {'Aadhar Card number': 'NO',
  'Address': '',
  'Age of  child as of today': '6 Years 8 Months 20 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Jun 11, 2014',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": 'vegetable/fruit seller',
  "Father's name ": 'Ram Gopal',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Factory worker',
  "Mother's name": 'Mamta',
  'Name of student': 'Monu',
  'Phone number (Father)': '',
  'Phone number (Mother)': 8860379021,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 5},
 {'Aadhar Card number': 888658899296,
  'Address': 'wz179',
  'Age of  child as of today': '5 Years 11 Months 6 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Mar 25, 2015',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Ajeet Kumar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Factory worker',
  "Mother's name": 'Gayatri',
  'Name of student': 'Anshuman',
  'Phone number (Father)': 7292012739,
  'Phone number (Mother)': 9918456281,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 6},
 {'Aadhar Card number': '',
  'Address': 'WZ  A34',
  'Age of  child as of today': '5 Years 9 Months 8 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'May 23, 2015',
  'Date of joining ': 'Oct 14, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Md Javed  ',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Afsana',
  'Name of student': 'Sana parveen',
  'Phone number (Father)': 9667250399,
  'Phone number (Mother)': 7838489531,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 7},
 {'Aadhar Card number': '',
  'Address': 'WZ-355',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Oct 16, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Naresh Paswan',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": '',
  "Mother's name": 'Rumi Devi',
  'Name of student': 'Deepanshi',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9319328305,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 8},
 {'Aadhar Card number': '',
  'Address': 'WZ-355',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Oct 16, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Naresh Paswan',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": '',
  "Mother's name": 'Rumi Devi',
  'Name of student': 'Shivam',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9319328305,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': '',
  'roll no ': 9},
 {'Aadhar Card number': 887919601607,
  'Address': 'WZ 2',
  'Age of  child as of today': '7 Years 5 Months 2 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Oct 1, 2013',
  'Date of joining ': 'Oct 13, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Sati Ram',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Poonam',
  'Name of student': 'Anshika',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9794465057,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 10},
 {'Aadhar Card number': 587466050373,
  'Address': 'WZ104',
  'Age of  child as of today': '7 Years 3 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Nov 30, 2013',
  'Date of joining ': 'Oct 17, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Manjeet Sah',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": 'Rita Devi',
  'Name of student': 'Love',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9315708762,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 11},
 {'Aadhar Card number': 381947310583,
  'Address': 'WZ104',
  'Age of  child as of today': '7 Years 3 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': 'shifted Renu R 15/2/21',
  'Date of birth ': 'Nov 30, 2013',
  'Date of joining ': 'Oct 17, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Manjeet Sah',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": 'Rita Devi',
  'Name of student': 'kush',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9315708762,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 12},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Oct 17, 2020',
  "Father' main occupation": '',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": '',
  'Name of student': 'Anjali',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 13},
 {'Aadhar Card number': 957645749738,
  'Address': 'WZ 286',
  'Age of  child as of today': '6 Years 2 Months 17 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': 'left school on Jan 31',
  'Date of birth ': 'Dec 14, 2014',
  'Date of joining ': 'Oct 17, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Asgar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'juhi',
  'Name of student': 'Ashraf',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9555657816,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1 A',
  'official Class': 1,
  'roll no ': 14},
 {'Aadhar Card number': 724425032353,
  'Address': '',
  'Age of  child as of today': '7 Years 1 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Feb 2, 2014',
  'Date of joining ': 'Oct 20, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Bablu Kumar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Kaushlya',
  'Name of student': 'kishan',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 15},
 {'Aadhar Card number': 764241486414,
  'Address': 'M-115',
  'Age of  child as of today': '6 Years 6 Months 22 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Aug 9, 2014',
  'Date of joining ': 'Oct 21, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Ranjeet Kumar',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Reena kumari',
  'Name of student': 'Lakshay',
  'Phone number (Father)': '',
  'Phone number (Mother)': 8860147881,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 16},
 {'Aadhar Card number': 703608148115,
  'Address': 'WZ 7/C',
  'Age of  child as of today': '6 Years 3 Months 17 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': 'Nov 14, 2014',
  'Date of joining ': 'Oct 29, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Ram Sharan',
  'Goes to goverment school (0 for no or 1 for yes': 0,
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Nirza Devi',
  'Name of student': 'Arpita',
  'Phone number (Father)': '',
  'Phone number (Mother)': 8860477980,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1A',
  'official Class': '',
  'roll no ': 17},
 {'Aadhar Card number': 'NO',
  'Address': 'M168',
  'Age of  child as of today': '5 Years 11 Months 6 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': 'shifted Renu R 15/2/21',
  'Date of birth ': 'Mar 25, 2015',
  'Date of joining ': 'Nov 2, 2020',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Md Saddam',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Rubi',
  'Name of student': 'Mohd  Aayan',
  'Phone number (Father)': '',
  'Phone number (Mother)': 7292012739,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '1A',
  'official Class': '',
  'roll no ': 18},
 {'Aadhar Card number': 564033878965,
  'Address': 'M 192',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Nov 2, 2020',
  "Father' main occupation": 'domestic cleaner',
  "Father's name ": '24Nov pappu',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Mamta',
  'Name of student': 'Divyanshu OL',
  'Phone number (Father)': '',
  'Phone number (Mother)': 7065571002,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': 'I A',
  'official Class': '',
  'roll no ': 19},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': 'shifted kusum jan 18',
  'Date of birth ': '',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": '',
  'Name of student': 'Sumit 1',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': ' 1 OL',
  'official Class': '',
  'roll no ': 1},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '121 Years 2 Months 1 Days',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": '',
  'Name of student': 'Sumit 2',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': 'Nur',
  'official Class': '',
  'roll no ': 2},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": '',
  'Name of student': 'Zeeshan',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': ' 1 OL',
  'official Class': '',
  'roll no ': 3},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": '',
  'Name of student': 'Sazia',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': ' 1 OL',
  'official Class': '',
  'roll no ': 4},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'domestic cleaner',
  "Mother's name": '',
  'Name of student': 'priyanka',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': ' 1 OL',
  'official Class': '',
  'roll no ': 5},
 {'Aadhar Card number': 669355684678,
  'Address': 'M192',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '4/2/2015',
  'Date of joining ': '',
  "Father' main occupation": 'Factory worker',
  "Father's name ": 'Ashok Kumar',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Katrina',
  'Name of student': 'Rohan 1A',
  'Phone number (Father)': '',
  'Phone number (Mother)': 8851346906,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': ' 1 OL',
  'official Class': '',
  'roll no ': 6},
 {'Aadhar Card number': 999399286674,
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '1/1/2014',
  'Date of joining ': 'N0V 1,2020',
  "Father' main occupation": 'Tailor',
  "Father's name ": 'Idris Ali',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": 'Housewife',
  "Mother's name": 'Najma Khatoon',
  'Name of student': ',Faizane Mustafa',
  'Phone number (Father)': '',
  'Phone number (Mother)': 8505882248,
  'Teacher': 'Abida',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 20},
 {'Aadhar Card number': 866982542849,
  'Address': 'WZ 72',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Dec 1, 2020',
  "Father' main occupation": 'other private',
  "Father's name ": 'Mani kanth Singh',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": 'Kavita',
  'Name of student': 'Abhishek',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 21},
 {'Aadhar Card number': 997433962494,
  'Address': 'WZ 20',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Dec 1, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Chote Khan',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": 'Rama Khan',
  'Name of student': 'Anas',
  'Phone number (Father)': 8810270945,
  'Phone number (Mother)': 9651137750,
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 22},
 {'Aadhar Card number': 347871862100,
  'Address': 'WZ 20',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Dec 1, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Chote Khan',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": 'Rama Khan',
  'Name of student': 'Mohd Alam',
  'Phone number (Father)': 8810270945,
  'Phone number (Mother)': 9651137750,
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 23},
 {'Aadhar Card number': '',
  'Address': 'WZ197',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': 'shifted Renu R 15/2/21',
  'Date of birth ': '1/5/2014',
  'Date of joining ': 'Dec 15, 2020',
  "Father' main occupation": '',
  "Father's name ": 'Nishant kumar',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": 'savita Devi',
  'Name of student': 'Ashish',
  'Phone number (Father)': 7209312148,
  'Phone number (Mother)': 9667385332,
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 24},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Dec 23, 2020',
  "Father' main occupation": '',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": '',
  'Name of student': 'Rahul',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 25},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': 'Jan 11, 2021',
  "Father' main occupation": '',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": '',
  'Name of student': 'Ayush',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 26},
 {'Aadhar Card number': 537329483700,
  'Address': 'WZ202',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '22/02/2012',
  'Date of joining ': 'Jan11,2021',
  "Father' main occupation": '',
  "Father's name ": 'Bablu singh',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": 'Shabnam Devi',
  'Name of student': 'Golu',
  'Phone number (Father)': '',
  'Phone number (Mother)': 9582315880,
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 27},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '20 Feb,2021',
  "Father' main occupation": '',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": '',
  'Name of student': 'priya',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 28},
 {'Aadhar Card number': '',
  'Address': '',
  'Age of  child as of today': '',
  'Baseline E': '',
  'Baseline Hindi': '',
  'Comment': '',
  'Date of birth ': '',
  'Date of joining ': '20 Feb,2021',
  "Father' main occupation": '',
  "Father's name ": '',
  'Goes to goverment school (0 for no or 1 for yes': '',
  "Mother' main occupation": '',
  "Mother's name": '',
  'Name of student': 'payal',
  'Phone number (Father)': '',
  'Phone number (Mother)': '',
  'Teacher': '',
  'baseline M': '',
  'gr #': '',
  'official Class': '',
  'roll no ': 29}]


class AuthView(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def check_authenticate(self):
        scopes = [
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive'
        ]
        credentials = Credentials.from_service_account_file(
            'teacher_credentials.json',
            scopes=scopes
        )
        gc = gspread.authorize(credentials)
        print('authorize')
        # ToDo: add check if actually authorized
        # ToDo: check if part of secret key is same part of teacher secret key in config
        app = App.get_running_app()
        app.root.current = 'teacher'
        app.root.ids.teacher_view.gc = gc
        if self.existing_link.text:
            app.root.ids.teacher_view.load_sheet(self.existing_link.text)
        else:
            app.root.ids.teacher_view.new_sheet()


class TeacherView(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # self.student_list.bind(minimum_height=self.student_list.setter('height'))
        self.sh = None
        self.student_master = {}
        self.headers = (
            'Date of joining',
            "roll no",
            "Name of student",
            "gr #",
            "Father's name",
            "Mother's name",
            "Address",
            "Phone number (Mother)",
            "Phone number (Father)",
            "Date of birth",
            "Aadhar Card number",
            "official Class",
            "Goes to goverment school (0 for no or 1 for yes",
            "Mother' main occupation",
            "Father' main occupation",
            "baseline M",
            "Baseline E",
            "Baseline Hindi",
            "Comment",
            "Age of  child as of today",
            "Teacher"
        )

    def new_sheet(self):
        sh = self.gc.create()
        # print(sh.sheet1.get('A1'))

    def load_sheet(self, link):
        self.sh = self.gc.open_by_url(link)
        print('open url')
        self.load_student_master()

    def load_student_master(self):
        ws = self.sh.worksheet("Student master")
        print('get worksheet')
        records = ws.get_all_records(head=2)
        # records = _TEST_DATA
        for student in records:
            student = {key.strip(): value for key, value in student.items()}
            std = AccordionItem(title=student["Name of student"])
            # std = BoxLayout(orientation='vertical', size_hint_y=None, height=500)
            # name = ToggleButton(text=student["Name of student"], group="students")
            # std.add_widget(name)
            bx = BoxLayout(orientation='vertical')
            std.add_widget(bx)
            for header in self.headers:
                key_value = BoxLayout(size_hint_y=None, height=20)
                key = Label(text=header)
                value = Label(text=str(student[header]))
                key_value.add_widget(key)
                key_value.add_widget(value)
                bx.add_widget(key_value)

            self.student_list.add_widget(std)


class MonitoringApp(App):
    def build(self):
        # ToDo: remove after testing:
        self.root.ids.first_name.text = 'Abida'
        self.root.ids.last_name.text = 'Teacher'
        self.root.ids.email.text = 'abida@gmail.com'
        self.root.ids.private_key.text = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD1kPVfoyWeBEJh\nUGdS4662qwp0qIctqOBRfvpRVYWuXZKqqxoszRN8L4QbnFa2o3ULgA4QfcXTNBZa\nV8GEe6ueOP875pVDJa+FIRPRg3B+S5tYkSZwRW7HeaMXcqr+4TWUsQv21EL04nEW\nNrWeP4XOEOXsUaU3hqIGaJVh1GZ7UiBxsc9VkOPV+Kx9vUjqu4Q3RrKLqFi4MYdo\nfZKEVAc7++9BsT8mlyS85S8ZsQnSt7A4JzDahu4rjf71fOp2sA3xC2zF2MVbPg0O\nhJH2ql2dqx1wsCb/RkXxGGcb/lG3FRkoCb0AzhRh98sg9Lzs2bSEHONWSCDlhCE1\n9eMXuW+xAgMBAAECggEAPWHXb+lCTyod5KDaPvYyNy9wbOIubgujTMO6cue3g3MY\n5QfhglbdusJO2a793ufjazU+bsFdmHJR7xG2CfV229U/+XtlDpSGN/chctLR5QPl\nqCEaNGCqtPpy+bq8QvtM7ybFSJTcysUqguS4h761peGD84siCwvghs0QIBTdbBAJ\nNVFb5H3sd0yNMwoNsOTqeop9KgNS+jwkoCuWQlnsqIQteAw/lo1c5Q9lIdqJgfJn\nPHHk7X9sstwbJtTY0UfH2YlDZ5J3VQz55Gpq9N1xAZTUli2ffbUt4JZeYZE8chyK\nVK5aw7JMqcfM7ne4abfP2du/k9kYu1VtaxcdbpF3hQKBgQD/XtbYB1A7Xuv1o7ui\n7Hh7W8iNmgjmWIFW+t5ax2PxOFOILkqWClCqmVEhYoBxOQ5ToNvSazYjE4/5fc/B\n32Zx1TIxlBIKDF0yA9A5Nbu5fg4Z+OrQ0ArDWfKmzcc2ZPj3oLGE/UfrxMhlL9cJ\nsbWO8SQMXRezWvb3acwJ7ondNQKBgQD2K+6UJ10GoXgiom6u58jREbQuBe81N01J\ngkAXrQ7LDkJujMMO0KYDtbkIPwCxeJmOTaZCI8C6PkMl2hCfffVToAhtFzBQZw14\n1q9HFi4L3itdzOl9x00s3xFLtl9MrnRu3S1+us5Yto5vb2CIDt6w2y/7KxN8NFh+\n8BX6X57kDQKBgQCYz/a+RPoU3QNT9YuFvf2Gy/CiE4e510Jmey5toh1DLpKFzjWh\nvUByJdavpJL5rcvN7Vc9fhxiNwWTpV6aRAW4nnwvwMxeqPFnyXJjmazhHfZwQky5\ncZTPO1cBy+emvBtjiwxPaYUNJ69HJa6HRYlApToOD/Lrx8Y7XVrUoqJq9QKBgQDX\nhF67Fjs7MuIacFq2hfYqE3XLVSa3UFM5p+60y63H2BQQ9OtQbRrq5I25ym6w8QR+\nsTx9aw+v/hKLcP5co8nEDLdTyplhytbglBOgCKsHeNo+pMdGdtX6EtDxmBiW6aTF\n6p2J9cHxqOHKbZf1hg8whrTbEDte4fUYLNkQ+eYBgQKBgAPTwAt5n8gw5cdGzFtL\nzBrpY4GtY5jHPGIEoP/w/NU+oy8OBuegtImTaQhZ999OYSGyNBXdLXnP+xQydsbM\nb4IKtY7oCLejodUmFdzDWn1K7GU3MwWCUvxoOH3ldzA+NOXXiSFOYrqnIrMrx3P0\nd0tYpWydA4FYUHR8Qg4UJDKj\n-----END PRIVATE KEY-----\n"
        self.root.ids.existing_link.text = 'https://docs.google.com/spreadsheets/d/1YsJGfi9c32wdVyIR-JpQwPnjRiIlM8mSWCZZjRiv-cM'


Factory.register('TeacherView', module='main')
Factory.register('AuthView', module='main')


if __name__ == '__main__':
    app = MonitoringApp()
    app.run()
